

module clk_gen (
     input                               clk_i_p
    ,input                               clk_i_n
    ,input                               rst_i                      // Asynchronous input from IBUF

    ,output                              sys_clk_o                  // system clock
    ,output                              sys_clk90_o                // system clock 90 degree phase
    ,output                              idelay_ref_clk_o           // idelay reference clock
    ,output                              axi_clk_o                  // axi clock
    ,output                              clock0_locked              // Locked signal from MMCM
    ,output                              clock1_locked              // Locked signal from MMCM
);

//***************************************************************************
// Function definitions
//***************************************************************************

//***************************************************************************
// Parameter definitions
//***************************************************************************

//***************************************************************************
// Reg declarations
//***************************************************************************

//***************************************************************************
// Wire declarations
//***************************************************************************

    wire                                clk_ibuf                    ;
    wire                                clk_bufg                    ;

//***************************************************************************
// Code
//***************************************************************************

    IBUFDS U_IBUFDS (
         .O                                  ( clk_ibuf                  ) // 1-bit output: Buffer output
        ,.I                                  ( clk_i_p                   ) // 1-bit input: Diff_p buffer input (connect directly to top-level port)
        ,.IB                                 ( clk_i_n                   ) // 1-bit input: Diff_n buffer input (connect directly to top-level port)
    );

    BUFG U_BUFG (
         .O                                  ( clk_bufg                  ) // 1-bit output: Clock output.
        ,.I                                  ( clk_ibuf                  ) // 1-bit input: Clock input.
    );

    // BUFG U_BUFG (
    //      .O                                  ( clk_bufg                  ) // 1-bit output: Clock output.
    //     ,.I                                  ( clk_i                     ) // 1-bit input: Clock input.
    // );

    // Instantiate clk_core - generated by the Clocking Wizard
    clk_wiz_0 U_CLK_WIZ_0 (
         .clk_out1                           ( idelay_ref_clk_o          ) // output clk_out1
        ,.clk_out2                           ( axi_clk_o                 ) // output clk_out2
        ,.locked                             ( clock0_locked             ) // output locked
        ,.reset                              ( rst_i                     )
        ,.clk_in1                            ( clk_bufg                  ) // input clk_in1, No buffer
    );

    clk_wiz_1 U_CLK_WIZ_1 (
         .clk_out1                           ( sys_clk_o                 ) // output clk_out1
        ,.clk_out2                           ( sys_clk90_o               ) // output clk_out2
        // ,.clk_out3                           ( sys_clk_5x_o              ) // output clk_out3
        ,.locked                             ( clock1_locked             ) // output locked
        ,.reset                              ( rst_i                     )
        ,.clk_in1                            ( clk_bufg                  ) // input clk_in1, No buffer
    );

endmodule
